# Generated by Django 5.0.7 on 2024-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_rename_photo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
